import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/intro",
        "getting-started/field",
        "getting-started/built-in-types",
      ],
    },
    /* {
      type: 'category',
      label: 'Basic Types',
      items: [],
    },
    {
      type: 'category',
      label: 'Making It Provable',
      items: [],
    }, */
    {
      type: "category",
      label: "API Reference",
      items: [
        {
          type: "autogenerated",
          dirName: "api-reference", // Generate sidebar slice from docs/api-reference
        },
      ],
    },
    {
      type: "doc",
      id: "changelog",
    },
  ],
};

export default sidebars;
