import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/intro",
        "getting-started/what-is-a-zk-constraint-system",
      ],
    },
    {
      type: "category",
      label: "Basic Types and Functions",
      collapsed: false,
      items: [
        "basic-types/field",
        "basic-types/int",
        "basic-types/keypairs-and-signatures",
        "basic-types/merkle-trees",
        "basic-types/arrays",
        "basic-types/structs",
        "basic-types/hashing",
      ],
    },
    {
      type: "category",
      label: "Writing Constraint Systems",
      collapsed: false,
      items: [
        "writing-constraint-systems/witnesses",
        "writing-constraint-systems/conditional-logic",
        "writing-constraint-systems/analyzing-constraint-systems",
        "writing-constraint-systems/zk-program",
      ],
    },
    {
      type: "category",
      label: "ZkApps",
      collapsed: true,
      items: [
        "zkapps/intro",
        "zkapps/smart-contracts",
        "zkapps/permissions",
        "zkapps/events",
        "zkapps/actions-and-reducers",
        "zkapps/account-updates",
        "zkapps/provable-inputs",
        "zkapps/zkprogram-proofs",
        "zkapps/local-development",
        "zkapps/deployment",
      ],
    },
    {
      type: "category",
      label: "Advanced Concepts",
      items: [
        "advanced-concepts/serialization",
        "advanced-concepts/recursion",
        "advanced-concepts/sideloaded-vks",
        {
          type: "category",
          label: "ZkApps",
          items: [
            "advanced-concepts/ZkApps/upgradability",
            "advanced-concepts/ZkApps/onChainPreconditions",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [
        {
          type: "category",
          label: "HMAC",
          items: [
            "tutorials/hmac/hmac-basics",
            "tutorials/hmac/implementation",
            "tutorials/hmac/tests",
          ],
        },
        {
          type: "category",
          label: "Frontend Integration",
          items: [
            "tutorials/frontent-integration-guides/angular",
            "tutorials/frontent-integration-guides/next",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "API Reference",
      link: {
        type: "doc",
        id: "api-reference/Introduction", // Set default page for this category
      },
      items: [
        {
          type: "autogenerated",
          dirName: "api-reference", // Generate sidebar slice from docs/api-reference
        },
      ],
    },
    {
      type: "doc",
      id: "changelog",
    },
  ],
};

export default sidebars;
