import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/intro",
        "getting-started/what-is-a-zk-constraint-system",
      ],
    },
    {
      type: "category",
      label: "Basic Types and Functions",
      collapsed: false,
      items: [
        "basic-types/field",
        "basic-types/int",
        "basic-types/keypairs-and-signatures",
        "basic-types/merkle-trees",
        "basic-types/arrays",
        "basic-types/structs",
        "basic-types/hashing",
      ],
    },
    /*
    {
      type: 'category',
      label: 'Making It Provable',
      items: [],
    }, */
    {
      type: "category",
      label: "API Reference",
      items: [
        {
          type: "autogenerated",
          dirName: "api-reference", // Generate sidebar slice from docs/api-reference
        },
      ],
    },
    {
      type: "doc",
      id: "changelog",
    },
  ],
};

export default sidebars;
